# Generated by Django 6.1.1 on 2026-10-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prediction', models.TextField()),
                ('split1', models.IntegerField(default=50)),
                ('split2', models.IntegerField(default=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentation.featureflag')),
            ],
        ),
    ]
